/********************************************************************************
** Form generated from reading UI file 'gs_windowone.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GS_WINDOWONE_H
#define UI_GS_WINDOWONE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GS_WindowOne
{
public:
    QAction *m_actionStartCollect;
    QAction *m_actionStopCollect;
    QAction *m_actionStartCircle;
    QAction *m_actionStopCircle;
    QAction *m_actionGenerateChart;
    QAction *m_actionExit;
    QAction *m_actionSetMySql;
    QAction *m_actionSetFrequency;
    QAction *m_actionSetAcquisition;
    QAction *m_actionHelp;
    QAction *action_2;
    QAction *m_actionOpen;
    QAction *m_actionSetIP;
    QAction *m_actionSetAcquisitionTwo;
    QAction *m_action_StartAll;
    QAction *m_action_StopAll;
    QAction *m_action_StopMysql;
    QAction *m_action_AcquisitionStart;
    QAction *m_action_AcquisitionStop;
    QWidget *centralWidget;
    QLabel *label_2;
    QLabel *label_3;
    QGroupBox *groupBox;
    QLabel *label_20;
    QLineEdit *m_lineED_Speed;
    QLineEdit *m_lineED_Frequency;
    QLineEdit *m_lineED_Current;
    QLabel *label;
    QLabel *label_6;
    QLabel *label_8;
    QLabel *label_10;
    QGroupBox *groupBox_2;
    QLabel *m_label_StatusTCP;
    QLabel *m_label_StatusFrequenc;
    QLabel *m_label_StatusMySqlW;
    QLabel *m_label_StatusAccquisition;
    QGroupBox *groupBox_3;
    QTextEdit *m_textED_theErrorInformation;
    QTabWidget *m_tabWidget_One;
    QWidget *widget;
    QFrame *m_frame_Distance;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_13;
    QLabel *m_label_DistanceOneRed;
    QLabel *m_label_DistanceTwoGreen;
    QLabel *label_14;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QWidget *tab_2;
    QFrame *m_frame_pressure;
    QLabel *label_7;
    QLabel *label_9;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *m_label_PressureARed;
    QLabel *m_label_PressureBGreen;
    QLabel *m_label_PressureCYellow;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QWidget *tab;
    QFrame *m_frame_tempture;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *m_label_TemptureARed;
    QLabel *m_label_TemptureBGreen;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QMenuBar *m_menuBar;
    QMenu *m_menuStart;
    QMenu *m_menuInstall;
    QMenu *m_menuOther;
    QMenu *menu;
    QToolBar *m_toolBar;
    QStatusBar *m_statusBar;

    void setupUi(QMainWindow *GS_WindowOne)
    {
        if (GS_WindowOne->objectName().isEmpty())
            GS_WindowOne->setObjectName(QStringLiteral("GS_WindowOne"));
        GS_WindowOne->resize(1269, 680);
        QFont font;
        font.setFamily(QString::fromUtf8("\347\255\211\347\272\277"));
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        GS_WindowOne->setFont(font);
        m_actionStartCollect = new QAction(GS_WindowOne);
        m_actionStartCollect->setObjectName(QStringLiteral("m_actionStartCollect"));
        QIcon icon;
        icon.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/1.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionStartCollect->setIcon(icon);
        m_actionStopCollect = new QAction(GS_WindowOne);
        m_actionStopCollect->setObjectName(QStringLiteral("m_actionStopCollect"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/2.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionStopCollect->setIcon(icon1);
        m_actionStartCircle = new QAction(GS_WindowOne);
        m_actionStartCircle->setObjectName(QStringLiteral("m_actionStartCircle"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/3.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionStartCircle->setIcon(icon2);
        m_actionStopCircle = new QAction(GS_WindowOne);
        m_actionStopCircle->setObjectName(QStringLiteral("m_actionStopCircle"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/4.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionStopCircle->setIcon(icon3);
        m_actionGenerateChart = new QAction(GS_WindowOne);
        m_actionGenerateChart->setObjectName(QStringLiteral("m_actionGenerateChart"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/5.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionGenerateChart->setIcon(icon4);
        m_actionExit = new QAction(GS_WindowOne);
        m_actionExit->setObjectName(QStringLiteral("m_actionExit"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/6.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionExit->setIcon(icon5);
        m_actionSetMySql = new QAction(GS_WindowOne);
        m_actionSetMySql->setObjectName(QStringLiteral("m_actionSetMySql"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/7.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionSetMySql->setIcon(icon6);
        m_actionSetFrequency = new QAction(GS_WindowOne);
        m_actionSetFrequency->setObjectName(QStringLiteral("m_actionSetFrequency"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/8.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionSetFrequency->setIcon(icon7);
        m_actionSetAcquisition = new QAction(GS_WindowOne);
        m_actionSetAcquisition->setObjectName(QStringLiteral("m_actionSetAcquisition"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/9.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionSetAcquisition->setIcon(icon8);
        m_actionHelp = new QAction(GS_WindowOne);
        m_actionHelp->setObjectName(QStringLiteral("m_actionHelp"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8("C:/Users/Administrator/Desktop/\345\233\276\346\240\207/10.png"), QSize(), QIcon::Normal, QIcon::Off);
        m_actionHelp->setIcon(icon9);
        action_2 = new QAction(GS_WindowOne);
        action_2->setObjectName(QStringLiteral("action_2"));
        m_actionOpen = new QAction(GS_WindowOne);
        m_actionOpen->setObjectName(QStringLiteral("m_actionOpen"));
        m_actionSetIP = new QAction(GS_WindowOne);
        m_actionSetIP->setObjectName(QStringLiteral("m_actionSetIP"));
        m_actionSetAcquisitionTwo = new QAction(GS_WindowOne);
        m_actionSetAcquisitionTwo->setObjectName(QStringLiteral("m_actionSetAcquisitionTwo"));
        m_action_StartAll = new QAction(GS_WindowOne);
        m_action_StartAll->setObjectName(QStringLiteral("m_action_StartAll"));
        m_action_StopAll = new QAction(GS_WindowOne);
        m_action_StopAll->setObjectName(QStringLiteral("m_action_StopAll"));
        m_action_StopMysql = new QAction(GS_WindowOne);
        m_action_StopMysql->setObjectName(QStringLiteral("m_action_StopMysql"));
        m_action_AcquisitionStart = new QAction(GS_WindowOne);
        m_action_AcquisitionStart->setObjectName(QStringLiteral("m_action_AcquisitionStart"));
        m_action_AcquisitionStop = new QAction(GS_WindowOne);
        m_action_AcquisitionStop->setObjectName(QStringLiteral("m_action_AcquisitionStop"));
        centralWidget = new QWidget(GS_WindowOne);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(30, 30, 91, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\347\255\211\347\272\277"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        label_2->setFont(font1);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(30, 70, 111, 41));
        label_3->setFont(font1);
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 10, 261, 151));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\347\255\211\347\272\277"));
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        groupBox->setFont(font2);
        groupBox->setStyleSheet(QStringLiteral(""));
        label_20 = new QLabel(groupBox);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 110, 81, 20));
        m_lineED_Speed = new QLineEdit(groupBox);
        m_lineED_Speed->setObjectName(QStringLiteral("m_lineED_Speed"));
        m_lineED_Speed->setGeometry(QRect(110, 20, 113, 31));
        m_lineED_Speed->setReadOnly(true);
        m_lineED_Frequency = new QLineEdit(groupBox);
        m_lineED_Frequency->setObjectName(QStringLiteral("m_lineED_Frequency"));
        m_lineED_Frequency->setGeometry(QRect(110, 60, 113, 31));
        m_lineED_Frequency->setReadOnly(true);
        m_lineED_Current = new QLineEdit(groupBox);
        m_lineED_Current->setObjectName(QStringLiteral("m_lineED_Current"));
        m_lineED_Current->setGeometry(QRect(110, 100, 113, 31));
        m_lineED_Current->setReadOnly(true);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(40, 200, 101, 21));
        label->setFont(font1);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(40, 230, 121, 41));
        label_6->setFont(font1);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(40, 270, 121, 41));
        label_8->setFont(font1);
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(40, 310, 141, 41));
        label_10->setFont(font1);
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 160, 261, 201));
        groupBox_2->setFont(font2);
        m_label_StatusTCP = new QLabel(groupBox_2);
        m_label_StatusTCP->setObjectName(QStringLiteral("m_label_StatusTCP"));
        m_label_StatusTCP->setGeometry(QRect(170, 40, 54, 21));
        m_label_StatusFrequenc = new QLabel(groupBox_2);
        m_label_StatusFrequenc->setObjectName(QStringLiteral("m_label_StatusFrequenc"));
        m_label_StatusFrequenc->setGeometry(QRect(170, 80, 54, 21));
        m_label_StatusMySqlW = new QLabel(groupBox_2);
        m_label_StatusMySqlW->setObjectName(QStringLiteral("m_label_StatusMySqlW"));
        m_label_StatusMySqlW->setGeometry(QRect(170, 120, 54, 21));
        m_label_StatusAccquisition = new QLabel(groupBox_2);
        m_label_StatusAccquisition->setObjectName(QStringLiteral("m_label_StatusAccquisition"));
        m_label_StatusAccquisition->setGeometry(QRect(170, 160, 54, 21));
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 370, 261, 221));
        groupBox_3->setFont(font2);
        m_textED_theErrorInformation = new QTextEdit(groupBox_3);
        m_textED_theErrorInformation->setObjectName(QStringLiteral("m_textED_theErrorInformation"));
        m_textED_theErrorInformation->setGeometry(QRect(10, 30, 241, 181));
        m_textED_theErrorInformation->setFont(font);
        m_textED_theErrorInformation->setReadOnly(true);
        m_tabWidget_One = new QTabWidget(centralWidget);
        m_tabWidget_One->setObjectName(QStringLiteral("m_tabWidget_One"));
        m_tabWidget_One->setGeometry(QRect(300, 0, 961, 581));
        m_tabWidget_One->setInputMethodHints(Qt::ImhNone);
        widget = new QWidget();
        widget->setObjectName(QStringLiteral("widget"));
        m_frame_Distance = new QFrame(widget);
        m_frame_Distance->setObjectName(QStringLiteral("m_frame_Distance"));
        m_frame_Distance->setGeometry(QRect(40, 10, 911, 471));
        m_frame_Distance->setFrameShape(QFrame::StyledPanel);
        m_frame_Distance->setFrameShadow(QFrame::Raised);
        label_4 = new QLabel(widget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 0, 31, 21));
        label_4->setFont(font2);
        label_5 = new QLabel(widget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 470, 31, 20));
        label_5->setFont(font2);
        label_13 = new QLabel(widget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(60, 500, 161, 31));
        QFont font3;
        font3.setPointSize(16);
        label_13->setFont(font3);
        m_label_DistanceOneRed = new QLabel(widget);
        m_label_DistanceOneRed->setObjectName(QStringLiteral("m_label_DistanceOneRed"));
        m_label_DistanceOneRed->setGeometry(QRect(230, 500, 54, 31));
        m_label_DistanceTwoGreen = new QLabel(widget);
        m_label_DistanceTwoGreen->setObjectName(QStringLiteral("m_label_DistanceTwoGreen"));
        m_label_DistanceTwoGreen->setGeometry(QRect(500, 500, 54, 31));
        label_14 = new QLabel(widget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(330, 500, 161, 31));
        label_14->setFont(font3);
        label_27 = new QLabel(widget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 400, 31, 20));
        label_27->setFont(font2);
        label_28 = new QLabel(widget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(20, 340, 31, 20));
        label_28->setFont(font2);
        label_29 = new QLabel(widget);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 270, 31, 20));
        label_29->setFont(font2);
        label_30 = new QLabel(widget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 200, 31, 20));
        label_30->setFont(font2);
        label_31 = new QLabel(widget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(20, 130, 31, 20));
        label_31->setFont(font2);
        label_32 = new QLabel(widget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(20, 60, 31, 20));
        label_32->setFont(font2);
        m_tabWidget_One->addTab(widget, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        m_frame_pressure = new QFrame(tab_2);
        m_frame_pressure->setObjectName(QStringLiteral("m_frame_pressure"));
        m_frame_pressure->setGeometry(QRect(40, 10, 911, 471));
        m_frame_pressure->setFrameShape(QFrame::StyledPanel);
        m_frame_pressure->setFrameShadow(QFrame::Raised);
        label_7 = new QLabel(tab_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, -10, 31, 41));
        label_7->setFont(font2);
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 460, 31, 41));
        label_9->setFont(font2);
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(60, 500, 71, 31));
        label_15->setFont(font3);
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(270, 500, 71, 31));
        label_16->setFont(font3);
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(490, 500, 71, 31));
        label_17->setFont(font3);
        m_label_PressureARed = new QLabel(tab_2);
        m_label_PressureARed->setObjectName(QStringLiteral("m_label_PressureARed"));
        m_label_PressureARed->setGeometry(QRect(150, 500, 54, 31));
        m_label_PressureBGreen = new QLabel(tab_2);
        m_label_PressureBGreen->setObjectName(QStringLiteral("m_label_PressureBGreen"));
        m_label_PressureBGreen->setGeometry(QRect(360, 500, 54, 31));
        m_label_PressureCYellow = new QLabel(tab_2);
        m_label_PressureCYellow->setObjectName(QStringLiteral("m_label_PressureCYellow"));
        m_label_PressureCYellow->setGeometry(QRect(580, 500, 54, 31));
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(20, 390, 31, 41));
        label_21->setFont(font2);
        label_22 = new QLabel(tab_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(20, 330, 31, 41));
        label_22->setFont(font2);
        label_23 = new QLabel(tab_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(20, 260, 31, 41));
        label_23->setFont(font2);
        label_24 = new QLabel(tab_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(20, 190, 31, 41));
        label_24->setFont(font2);
        label_25 = new QLabel(tab_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(20, 120, 31, 41));
        label_25->setFont(font2);
        label_26 = new QLabel(tab_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(20, 50, 31, 41));
        label_26->setFont(font2);
        m_tabWidget_One->addTab(tab_2, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        m_frame_tempture = new QFrame(tab);
        m_frame_tempture->setObjectName(QStringLiteral("m_frame_tempture"));
        m_frame_tempture->setGeometry(QRect(40, 10, 911, 471));
        m_frame_tempture->setFrameShape(QFrame::StyledPanel);
        m_frame_tempture->setFrameShadow(QFrame::Raised);
        label_11 = new QLabel(tab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(20, -10, 41, 41));
        label_11->setFont(font2);
        label_12 = new QLabel(tab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 460, 31, 41));
        label_12->setFont(font2);
        label_18 = new QLabel(tab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(100, 500, 81, 31));
        label_18->setFont(font3);
        label_19 = new QLabel(tab);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(350, 500, 81, 31));
        label_19->setFont(font3);
        m_label_TemptureARed = new QLabel(tab);
        m_label_TemptureARed->setObjectName(QStringLiteral("m_label_TemptureARed"));
        m_label_TemptureARed->setGeometry(QRect(200, 500, 61, 31));
        m_label_TemptureBGreen = new QLabel(tab);
        m_label_TemptureBGreen->setObjectName(QStringLiteral("m_label_TemptureBGreen"));
        m_label_TemptureBGreen->setGeometry(QRect(450, 500, 61, 31));
        label_33 = new QLabel(tab);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 390, 31, 41));
        label_33->setFont(font2);
        label_34 = new QLabel(tab);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(20, 330, 31, 41));
        label_34->setFont(font2);
        label_35 = new QLabel(tab);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(20, 260, 31, 41));
        label_35->setFont(font2);
        label_36 = new QLabel(tab);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(20, 190, 31, 41));
        label_36->setFont(font2);
        label_37 = new QLabel(tab);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(20, 120, 31, 41));
        label_37->setFont(font2);
        label_38 = new QLabel(tab);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(20, 50, 31, 41));
        label_38->setFont(font2);
        m_tabWidget_One->addTab(tab, QString());
        GS_WindowOne->setCentralWidget(centralWidget);
        groupBox_3->raise();
        groupBox_2->raise();
        groupBox->raise();
        label_2->raise();
        label_3->raise();
        label->raise();
        label_6->raise();
        label_8->raise();
        label_10->raise();
        m_tabWidget_One->raise();
        m_menuBar = new QMenuBar(GS_WindowOne);
        m_menuBar->setObjectName(QStringLiteral("m_menuBar"));
        m_menuBar->setGeometry(QRect(0, 0, 1269, 23));
        m_menuBar->setNativeMenuBar(true);
        m_menuStart = new QMenu(m_menuBar);
        m_menuStart->setObjectName(QStringLiteral("m_menuStart"));
        m_menuInstall = new QMenu(m_menuBar);
        m_menuInstall->setObjectName(QStringLiteral("m_menuInstall"));
        m_menuOther = new QMenu(m_menuBar);
        m_menuOther->setObjectName(QStringLiteral("m_menuOther"));
        menu = new QMenu(m_menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        GS_WindowOne->setMenuBar(m_menuBar);
        m_toolBar = new QToolBar(GS_WindowOne);
        m_toolBar->setObjectName(QStringLiteral("m_toolBar"));
        m_toolBar->setFont(font);
        GS_WindowOne->addToolBar(Qt::TopToolBarArea, m_toolBar);
        m_statusBar = new QStatusBar(GS_WindowOne);
        m_statusBar->setObjectName(QStringLiteral("m_statusBar"));
        GS_WindowOne->setStatusBar(m_statusBar);

        m_menuBar->addAction(m_menuStart->menuAction());
        m_menuBar->addAction(m_menuInstall->menuAction());
        m_menuBar->addAction(m_menuOther->menuAction());
        m_menuBar->addAction(menu->menuAction());
        m_menuStart->addAction(m_actionStartCircle);
        m_menuStart->addAction(m_actionStopCircle);
        m_menuStart->addAction(m_actionGenerateChart);
        m_menuStart->addAction(m_actionExit);
        m_menuInstall->addAction(m_actionSetMySql);
        m_menuInstall->addAction(m_actionSetFrequency);
        m_menuInstall->addAction(m_actionSetAcquisition);
        m_menuInstall->addAction(m_actionSetIP);
        m_menuOther->addAction(m_actionHelp);
        menu->addAction(m_actionOpen);
        m_toolBar->addSeparator();
        m_toolBar->addAction(m_action_StartAll);
        m_toolBar->addSeparator();
        m_toolBar->addAction(m_action_StopAll);
        m_toolBar->addSeparator();
        m_toolBar->addAction(m_action_StopMysql);
        m_toolBar->addSeparator();
        m_toolBar->addAction(m_action_AcquisitionStart);
        m_toolBar->addSeparator();
        m_toolBar->addAction(m_action_AcquisitionStop);

        retranslateUi(GS_WindowOne);

        m_tabWidget_One->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(GS_WindowOne);
    } // setupUi

    void retranslateUi(QMainWindow *GS_WindowOne)
    {
        GS_WindowOne->setWindowTitle(QApplication::translate("GS_WindowOne", "\347\251\272\346\260\224\350\275\264\346\211\277\346\265\213\350\257\225\345\217\260", Q_NULLPTR));
        m_actionStartCollect->setText(QApplication::translate("GS_WindowOne", "\346\265\213\350\257\225\345\274\200\345\247\213", Q_NULLPTR));
        m_actionStopCollect->setText(QApplication::translate("GS_WindowOne", "\346\265\213\350\257\225\347\273\223\346\235\237", Q_NULLPTR));
        m_actionStartCircle->setText(QApplication::translate("GS_WindowOne", "\350\275\254\345\212\250\345\274\200\345\247\213", Q_NULLPTR));
        m_actionStopCircle->setText(QApplication::translate("GS_WindowOne", "\350\275\254\345\212\250\347\273\223\346\235\237", Q_NULLPTR));
        m_actionGenerateChart->setText(QApplication::translate("GS_WindowOne", "\347\224\237\346\210\220\345\233\276\345\203\217", Q_NULLPTR));
        m_actionExit->setText(QApplication::translate("GS_WindowOne", "\351\200\200\345\207\272", Q_NULLPTR));
        m_actionSetMySql->setText(QApplication::translate("GS_WindowOne", "\346\225\260\346\215\256\345\272\223", Q_NULLPTR));
        m_actionSetFrequency->setText(QApplication::translate("GS_WindowOne", "\345\217\230\351\242\221\345\231\250", Q_NULLPTR));
        m_actionSetAcquisition->setText(QApplication::translate("GS_WindowOne", "\351\207\207\351\233\206\345\215\241", Q_NULLPTR));
        m_actionHelp->setText(QApplication::translate("GS_WindowOne", "\345\270\256\345\212\251", Q_NULLPTR));
        action_2->setText(QApplication::translate("GS_WindowOne", "\344\270\200\351\224\256\345\274\200\345\220\257", Q_NULLPTR));
        m_actionOpen->setText(QApplication::translate("GS_WindowOne", "\350\275\254\351\200\237\345\205\263\347\263\273\345\233\276", Q_NULLPTR));
        m_actionSetIP->setText(QApplication::translate("GS_WindowOne", "\347\275\221\347\273\234\345\217\202\346\225\260", Q_NULLPTR));
        m_actionSetAcquisitionTwo->setText(QApplication::translate("GS_WindowOne", "\351\207\207\351\233\206\345\215\2412", Q_NULLPTR));
        m_action_StartAll->setText(QApplication::translate("GS_WindowOne", "\344\270\200\351\224\256\345\220\257\345\212\250", Q_NULLPTR));
        m_action_StopAll->setText(QApplication::translate("GS_WindowOne", "\344\270\200\351\224\256\347\273\223\346\235\237", Q_NULLPTR));
        m_action_StopMysql->setText(QApplication::translate("GS_WindowOne", "\345\205\263\351\227\255\346\225\260\346\215\256\345\206\231\345\205\245", Q_NULLPTR));
        m_action_AcquisitionStart->setText(QApplication::translate("GS_WindowOne", "\351\207\207\351\233\206\345\274\200\345\247\213", Q_NULLPTR));
        m_action_AcquisitionStop->setText(QApplication::translate("GS_WindowOne", "\351\207\207\351\233\206\347\273\223\346\235\237", Q_NULLPTR));
        label_2->setText(QApplication::translate("GS_WindowOne", "\345\275\223\345\211\215\350\275\254\351\200\237:", Q_NULLPTR));
        label_3->setText(QApplication::translate("GS_WindowOne", "\345\275\223\345\211\215\351\242\221\347\216\207:", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("GS_WindowOne", " \345\256\236\346\227\266\345\217\202\346\225\260:", Q_NULLPTR));
        label_20->setText(QApplication::translate("GS_WindowOne", "\345\275\223\345\211\215\347\224\265\346\265\201:", Q_NULLPTR));
        label->setText(QApplication::translate("GS_WindowOne", "TCP\351\200\232\350\256\257\347\212\266\346\200\201:", Q_NULLPTR));
        label_6->setText(QApplication::translate("GS_WindowOne", "\345\217\230\351\242\221\345\231\250\351\200\232\350\256\257\347\212\266\346\200\201:", Q_NULLPTR));
        label_8->setText(QApplication::translate("GS_WindowOne", "\346\225\260\346\215\256\345\272\223\347\212\266\346\200\201:", Q_NULLPTR));
        label_10->setText(QApplication::translate("GS_WindowOne", "\346\225\260\346\215\256\351\207\207\351\233\206\347\212\266\346\200\201:", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("GS_WindowOne", "\347\212\266\346\200\201:", Q_NULLPTR));
        m_label_StatusTCP->setText(QString());
        m_label_StatusFrequenc->setText(QString());
        m_label_StatusMySqlW->setText(QString());
        m_label_StatusAccquisition->setText(QString());
        groupBox_3->setTitle(QApplication::translate("GS_WindowOne", "\346\212\245\351\224\231\346\240\217:", Q_NULLPTR));
        label_4->setText(QApplication::translate("GS_WindowOne", "6V", Q_NULLPTR));
        label_5->setText(QApplication::translate("GS_WindowOne", "-1V", Q_NULLPTR));
        label_13->setText(QApplication::translate("GS_WindowOne", "\347\272\242\345\244\226\347\272\277\346\265\213\350\267\235\344\273\252A:", Q_NULLPTR));
        m_label_DistanceOneRed->setText(QString());
        m_label_DistanceTwoGreen->setText(QString());
        label_14->setText(QApplication::translate("GS_WindowOne", "\347\272\242\345\244\226\347\272\277\346\265\213\350\267\235\344\273\252B:", Q_NULLPTR));
        label_27->setText(QApplication::translate("GS_WindowOne", "0V", Q_NULLPTR));
        label_28->setText(QApplication::translate("GS_WindowOne", "1V", Q_NULLPTR));
        label_29->setText(QApplication::translate("GS_WindowOne", "2V", Q_NULLPTR));
        label_30->setText(QApplication::translate("GS_WindowOne", "3V", Q_NULLPTR));
        label_31->setText(QApplication::translate("GS_WindowOne", "4V", Q_NULLPTR));
        label_32->setText(QApplication::translate("GS_WindowOne", "5V", Q_NULLPTR));
        m_tabWidget_One->setTabText(m_tabWidget_One->indexOf(widget), QApplication::translate("GS_WindowOne", "\347\272\242\345\244\226\346\265\213\350\267\235", Q_NULLPTR));
        label_7->setText(QApplication::translate("GS_WindowOne", "6V", Q_NULLPTR));
        label_9->setText(QApplication::translate("GS_WindowOne", "-1V", Q_NULLPTR));
        label_15->setText(QApplication::translate("GS_WindowOne", "\345\216\213\345\212\233A\357\274\232", Q_NULLPTR));
        label_16->setText(QApplication::translate("GS_WindowOne", "\345\216\213\345\212\233B\357\274\232", Q_NULLPTR));
        label_17->setText(QApplication::translate("GS_WindowOne", "\345\216\213\345\212\233C\357\274\232", Q_NULLPTR));
        m_label_PressureARed->setText(QString());
        m_label_PressureBGreen->setText(QString());
        m_label_PressureCYellow->setText(QString());
        label_21->setText(QApplication::translate("GS_WindowOne", "0V", Q_NULLPTR));
        label_22->setText(QApplication::translate("GS_WindowOne", "1V", Q_NULLPTR));
        label_23->setText(QApplication::translate("GS_WindowOne", "2V", Q_NULLPTR));
        label_24->setText(QApplication::translate("GS_WindowOne", "3V", Q_NULLPTR));
        label_25->setText(QApplication::translate("GS_WindowOne", "4V", Q_NULLPTR));
        label_26->setText(QApplication::translate("GS_WindowOne", "5V", Q_NULLPTR));
        m_tabWidget_One->setTabText(m_tabWidget_One->indexOf(tab_2), QApplication::translate("GS_WindowOne", "\345\216\213\345\212\233", Q_NULLPTR));
        label_11->setText(QApplication::translate("GS_WindowOne", "6V", Q_NULLPTR));
        label_12->setText(QApplication::translate("GS_WindowOne", "-1V", Q_NULLPTR));
        label_18->setText(QApplication::translate("GS_WindowOne", " \346\270\251\345\272\246A\357\274\232", Q_NULLPTR));
        label_19->setText(QApplication::translate("GS_WindowOne", " \346\270\251\345\272\246B\357\274\232", Q_NULLPTR));
        m_label_TemptureARed->setText(QString());
        m_label_TemptureBGreen->setText(QString());
        label_33->setText(QApplication::translate("GS_WindowOne", "0V", Q_NULLPTR));
        label_34->setText(QApplication::translate("GS_WindowOne", "1V", Q_NULLPTR));
        label_35->setText(QApplication::translate("GS_WindowOne", "2V", Q_NULLPTR));
        label_36->setText(QApplication::translate("GS_WindowOne", "3V", Q_NULLPTR));
        label_37->setText(QApplication::translate("GS_WindowOne", "4V", Q_NULLPTR));
        label_38->setText(QApplication::translate("GS_WindowOne", "5V", Q_NULLPTR));
        m_tabWidget_One->setTabText(m_tabWidget_One->indexOf(tab), QApplication::translate("GS_WindowOne", " \346\270\251\345\272\246", Q_NULLPTR));
        m_menuStart->setTitle(QApplication::translate("GS_WindowOne", "\345\274\200\345\247\213", Q_NULLPTR));
        m_menuInstall->setTitle(QApplication::translate("GS_WindowOne", "\350\256\276\347\275\256", Q_NULLPTR));
        m_menuOther->setTitle(QApplication::translate("GS_WindowOne", "\345\205\266\344\273\226", Q_NULLPTR));
        menu->setTitle(QApplication::translate("GS_WindowOne", "\347\252\227\345\217\243", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class GS_WindowOne: public Ui_GS_WindowOne {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GS_WINDOWONE_H
